export const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  SUBTRACT_ITEM_FROM_CART: "SUBTRACT_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};
